import { Tenant } from '@/types/tenant';
import { Contact, PipelineDeal, ActivityLog } from '@/types/crm';
import { ChatSession, WhatsAppMessage } from '@/types/whatsapp';
import { INDUSTRY_PRESETS } from './solid/IndustryPresets';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant_realestate_01',
    name: 'Inmobiliaria Costa Sol',
    slug: 'costasol',
    industry: 'real_estate',
    plan: 'pro',
    currency: 'USD',
    theme: {
      primaryColor: '#0284c7',
      secondaryColor: '#0369a1',
      accentColor: '#38bdf8',
      darkModeDefault: true,
      logoUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=100&auto=format&fit=crop&q=60',
    },
    stages: INDUSTRY_PRESETS.real_estate.defaultStages,
    customFields: [...INDUSTRY_PRESETS.real_estate.contactFields, ...INDUSTRY_PRESETS.real_estate.dealFields],
    whatsappBotPrompt: INDUSTRY_PRESETS.real_estate.botSystemPromptTemplate,
    whatsappAutoReply: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tenant_medical_02',
    name: 'Clínica San Gabriel',
    slug: 'sangabriel',
    industry: 'medical',
    plan: 'enterprise',
    currency: 'PEN',
    theme: {
      primaryColor: '#0d9488',
      secondaryColor: '#0f766e',
      accentColor: '#2dd4bf',
      darkModeDefault: true,
    },
    stages: INDUSTRY_PRESETS.medical.defaultStages,
    customFields: [...INDUSTRY_PRESETS.medical.contactFields, ...INDUSTRY_PRESETS.medical.dealFields],
    whatsappBotPrompt: INDUSTRY_PRESETS.medical.botSystemPromptTemplate,
    whatsappAutoReply: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tenant_retail_03',
    name: 'Mizu Store Ecommerce',
    slug: 'mizu',
    industry: 'retail',
    plan: 'pro',
    currency: 'PEN',
    theme: {
      primaryColor: '#f97316',
      secondaryColor: '#c2410c',
      accentColor: '#fb923c',
      darkModeDefault: true,
    },
    stages: INDUSTRY_PRESETS.retail.defaultStages,
    customFields: [...INDUSTRY_PRESETS.retail.contactFields, ...INDUSTRY_PRESETS.retail.dealFields],
    whatsappBotPrompt: INDUSTRY_PRESETS.retail.botSystemPromptTemplate,
    whatsappAutoReply: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cont_1',
    tenantId: 'tenant_realestate_01',
    name: 'Carlos Mendoza',
    email: 'carlos.mendoza@gmail.com',
    phone: '+51 969 123 456',
    company: 'Inversiones CM',
    status: 'lead',
    tags: ['Comprador VIP', 'Zona Norte'],
    customData: {
      clientType: 'comprador',
      budgetRange: '$120,000 - $180,000',
      preferredZone: 'Los Ejidos, Piura',
    },
    notes: 'Interesado en casa de 3 dormitorios con jardín.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont_2',
    tenantId: 'tenant_realestate_01',
    name: 'Mariana Flores',
    email: 'mariana.f@outlook.com',
    phone: '+51 984 567 890',
    company: 'Consultora Alfa',
    status: 'active',
    tags: ['Arrendatario', 'Urgente'],
    customData: {
      clientType: 'arrendatario',
      budgetRange: '$800 / mes',
      preferredZone: 'Miraflores',
    },
    notes: 'Busca departamento amoblado para mudanza en 15 días.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont_3',
    tenantId: 'tenant_realestate_01',
    name: 'Roberto Benites',
    email: 'r.benites@constructora.pe',
    phone: '+51 950 998 776',
    company: 'Constructora del Norte',
    status: 'customer',
    tags: ['Inversionista', 'Terrenos'],
    customData: {
      clientType: 'inversionista',
      budgetRange: '$300,000+',
      preferredZone: 'Carretera Paita',
    },
    notes: 'Comprador recurrente de lotes para desarrollo inmobiliario.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_DEALS: PipelineDeal[] = [
  {
    id: 'deal_1',
    tenantId: 'tenant_realestate_01',
    title: 'Casa Quinta Los Ejidos 250m2',
    value: 145000,
    stageId: 'stage_visit',
    contactId: 'cont_1',
    contactName: 'Carlos Mendoza',
    contactPhone: '+51 969 123 456',
    priority: 'high',
    expectedCloseDate: new Date(Date.now() + 3600000 * 24 * 7).toISOString(),
    customData: {
      propertyType: 'casa',
      propertyCode: 'CASA-EJI-04',
      bedrooms: 3,
    },
    notes: 'Visita agendada para el sábado a las 10:00 AM.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal_2',
    tenantId: 'tenant_realestate_01',
    title: 'Dpto Duplex Frente a Parque',
    value: 92000,
    stageId: 'stage_offer',
    contactId: 'cont_2',
    contactName: 'Mariana Flores',
    contactPhone: '+51 984 567 890',
    priority: 'medium',
    expectedCloseDate: new Date(Date.now() + 3600000 * 24 * 3).toISOString(),
    customData: {
      propertyType: 'departamento',
      propertyCode: 'DPTO-DUP-201',
      bedrooms: 2,
    },
    notes: 'Enviada carta de oferta formal con separación.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal_3',
    tenantId: 'tenant_realestate_01',
    title: 'Lote Comercial 1,200m2',
    value: 280000,
    stageId: 'stage_won',
    contactId: 'cont_3',
    contactName: 'Roberto Benites',
    contactPhone: '+51 950 998 776',
    priority: 'high',
    expectedCloseDate: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
    customData: {
      propertyType: 'terreno',
      propertyCode: 'TER-COM-01',
      bedrooms: 0,
    },
    notes: 'Contrato de compraventa firmado ante notario.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act_1',
    tenantId: 'tenant_realestate_01',
    type: 'deal_moved',
    title: 'Oportunidad Avanzada a Visita Agendada',
    description: 'Casa Quinta Los Ejidos 250m2 fue movida a Visita Agendada por asesor.',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    entityId: 'deal_1',
    entityType: 'deal',
  },
  {
    id: 'act_2',
    tenantId: 'tenant_realestate_01',
    type: 'whatsapp_message',
    title: 'Consulta Recibida por WhatsApp',
    description: 'Nuevo mensaje de Carlos Mendoza: "¿Cuándo podemos coordinar la visita a la propiedad?"',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    entityId: 'cont_1',
    entityType: 'whatsapp',
  },
  {
    id: 'act_3',
    tenantId: 'tenant_realestate_01',
    type: 'deal_created',
    title: 'Nueva Oportunidad Creada',
    description: 'Dpto Duplex Frente a Parque ($92,000) asignado a Mariana Flores.',
    timestamp: new Date(Date.now() - 3600000 * 24 * 4).toISOString(),
    entityId: 'deal_2',
    entityType: 'deal',
  },
];

export const INITIAL_CHATS: ChatSession[] = [
  {
    id: 'chat_1',
    tenantId: 'tenant_realestate_01',
    phoneNumber: '+51 969 123 456',
    contactName: 'Carlos Mendoza',
    unreadCount: 0,
    lastMessage: 'Excelente, estaré puntual el sábado a las 10am.',
    lastMessageTime: new Date(Date.now() - 3600000 * 1).toISOString(),
    contactId: 'cont_1',
    stage: 'Visita Agendada',
    isAiEnabled: true,
  },
  {
    id: 'chat_2',
    tenantId: 'tenant_realestate_01',
    phoneNumber: '+51 984 567 890',
    contactName: 'Mariana Flores',
    unreadCount: 1,
    lastMessage: 'Hola, ¿el departamento incluye cochera techada?',
    lastMessageTime: new Date(Date.now() - 3600000 * 3).toISOString(),
    contactId: 'cont_2',
    stage: 'Propuesta / Separación',
    isAiEnabled: true,
  },
];

export const INITIAL_MESSAGES: Record<string, WhatsAppMessage[]> = {
  chat_1: [
    {
      id: 'msg_1_1',
      tenantId: 'tenant_realestate_01',
      chatId: 'chat_1',
      sender: 'user',
      text: 'Hola buenas tardes, vi en su web la casa en Los Ejidos. ¿Sigue disponible?',
      timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_1_2',
      tenantId: 'tenant_realestate_01',
      chatId: 'chat_1',
      sender: 'bot',
      text: '¡Hola Carlos! Sí, la propiedad Casa Quinta Los Ejidos (Cód. CASA-EJI-04) se encuentra 100% disponible. Cuenta con 250m2, 3 dormitorios y cochera doble. ¿Te gustaría agendar una visita este sábado por la mañana?',
      timestamp: new Date(Date.now() - 3600000 * 3 + 15000).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_1_3',
      tenantId: 'tenant_realestate_01',
      chatId: 'chat_1',
      sender: 'user',
      text: 'Excelente, estaré puntual el sábado a las 10am.',
      timestamp: new Date(Date.now() - 3600000 * 1).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_1_4',
      tenantId: 'tenant_realestate_01',
      chatId: 'chat_1',
      sender: 'bot',
      text: '¡Perfecto! Hemos agendado tu visita para el sábado a las 10:00 AM. Nuestro asesor comercial te esperará en la entrada principal. ¡Gracias por confiar en Costa Sol!',
      timestamp: new Date(Date.now() - 3600000 * 1 + 10000).toISOString(),
      status: 'read',
    },
  ],
  chat_2: [
    {
      id: 'msg_2_1',
      tenantId: 'tenant_realestate_01',
      chatId: 'chat_2',
      sender: 'user',
      text: 'Hola, ¿el departamento incluye cochera techada?',
      timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
      status: 'read',
    },
  ],
};
